// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void PhysicsStepHandler(ReducerEventContext ctx, PhysicsStepTimer timer);
    public event PhysicsStepHandler? OnPhysicsStep;

    public void PhysicsStep(PhysicsStepTimer timer) {
      conn.InternalCallReducer(new Reducer.PhysicsStep(timer), this.SetCallReducerFlags.PhysicsStepFlags);
    }

    public bool InvokePhysicsStep(ReducerEventContext ctx, Reducer.PhysicsStep args) {
      if (OnPhysicsStep == null) {
        if (InternalOnUnhandledReducerError != null) {
          switch (ctx.Event.Status) {
            case Status.Failed(var reason):
              InternalOnUnhandledReducerError(ctx, new Exception(reason));
              break;
            case Status.OutOfEnergy(var _):
              InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
              break;
          }
        }
        return false;
      }
      OnPhysicsStep(
          ctx,
          args.Timer
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PhysicsStep : Reducer, IReducerArgs {
      [DataMember(Name = "_timer")]
      public PhysicsStepTimer Timer;

      public PhysicsStep(PhysicsStepTimer Timer) {
        this.Timer = Timer;
      }

      public PhysicsStep() {
        this.Timer = new();
      }

      string IReducerArgs.ReducerName => "physics_step";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags PhysicsStepFlags;
    public void PhysicsStep(CallReducerFlags flags) => PhysicsStepFlags = flags;
  }
}
