[package]
name = "justmaple"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# See: https://docs.rs/spacetimedb/latest/spacetimedb/ for SpacetimeDB Rust SDK
spacetimedb = "1.3.0"
log = "0.4.17"
