// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class MovementControllerHandle : RemoteTableHandle<EventContext, MovementController> {
      protected override string RemoteTableName => "movement_controller";

      public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint> {
        protected override uint GetKey(MovementController row) => row.EntityId;

        public EntityIdUniqueIndex(MovementControllerHandle table) : base(table) { }
      }

      public readonly EntityIdUniqueIndex EntityId;

      public sealed class PlayerIdIndex : BTreeIndexBase<uint> {
        protected override uint GetKey(MovementController row) => row.PlayerId;

        public PlayerIdIndex(MovementControllerHandle table) : base(table) { }
      }

      public readonly PlayerIdIndex PlayerId;

      internal MovementControllerHandle(DbConnection conn) : base(conn) {
        EntityId = new(this);
        PlayerId = new(this);
      }

      protected override object GetPrimaryKey(MovementController row) => row.EntityId;
    }

    public readonly MovementControllerHandle MovementController;
  }
}
