// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class PhysicsStepTimerHandle : RemoteTableHandle<EventContext, PhysicsStepTimer> {
      protected override string RemoteTableName => "physics_step_timer";

      public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong> {
        protected override ulong GetKey(PhysicsStepTimer row) => row.ScheduledId;

        public ScheduledIdUniqueIndex(PhysicsStepTimerHandle table) : base(table) { }
      }

      public readonly ScheduledIdUniqueIndex ScheduledId;

      internal PhysicsStepTimerHandle(DbConnection conn) : base(conn) {
        ScheduledId = new(this);
      }

      protected override object GetPrimaryKey(PhysicsStepTimer row) => row.ScheduledId;
    }

    public readonly PhysicsStepTimerHandle PhysicsStepTimer;
  }
}
