// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class PlayerInputHandle : RemoteTableHandle<EventContext, PlayerInput> {
      protected override string RemoteTableName => "player_input";

      public sealed class PlayerIdUniqueIndex : UniqueIndexBase<uint> {
        protected override uint GetKey(PlayerInput row) => row.PlayerId;

        public PlayerIdUniqueIndex(PlayerInputHandle table) : base(table) { }
      }

      public readonly PlayerIdUniqueIndex PlayerId;

      internal PlayerInputHandle(DbConnection conn) : base(conn) {
        PlayerId = new(this);
      }

      protected override object GetPrimaryKey(PlayerInput row) => row.PlayerId;
    }

    public readonly PlayerInputHandle PlayerInput;
  }
}
