// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  public enum BodyType {
    Dynamic,
    Static,
    KinematicPositionBased,
    KinematicVelocityBased,
  }
}
