// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class Entity {
    [DataMember(Name = "entity_id")]
    public uint EntityId;
    [DataMember(Name = "position")]
    public DbVector2 Position;
    [DataMember(Name = "velocity")]
    public DbVector2 Velocity;
    [DataMember(Name = "mass")]
    public uint Mass;
    [DataMember(Name = "entity_type")]
    public EntityType EntityType;

    public Entity(
        uint EntityId,
        DbVector2 Position,
        DbVector2 Velocity,
        uint Mass,
        EntityType EntityType
    ) {
      this.EntityId = EntityId;
      this.Position = Position;
      this.Velocity = Velocity;
      this.Mass = Mass;
      this.EntityType = EntityType;
    }

    public Entity() {
      this.Position = new();
      this.Velocity = new();
    }
  }
}
