// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class MovementController {
    [DataMember(Name = "entity_id")]
    public uint EntityId;
    [DataMember(Name = "player_id")]
    public uint PlayerId;
    [DataMember(Name = "move_speed")]
    public float MoveSpeed;
    [DataMember(Name = "jump_force")]
    public float JumpForce;
    [DataMember(Name = "can_jump")]
    public bool CanJump;

    public MovementController(
        uint EntityId,
        uint PlayerId,
        float MoveSpeed,
        float JumpForce,
        bool CanJump
    ) {
      this.EntityId = EntityId;
      this.PlayerId = PlayerId;
      this.MoveSpeed = MoveSpeed;
      this.JumpForce = JumpForce;
      this.CanJump = CanJump;
    }

    public MovementController() {
    }
  }
}
