// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class PhysicsBody {
    [DataMember(Name = "entity_id")]
    public uint EntityId;
    [DataMember(Name = "body_type")]
    public BodyType BodyType;
    [DataMember(Name = "on_ground")]
    public bool OnGround;
    [DataMember(Name = "collision_groups")]
    public ushort CollisionGroups;

    public PhysicsBody(
        uint EntityId,
        BodyType BodyType,
        bool OnGround,
        ushort CollisionGroups
    ) {
      this.EntityId = EntityId;
      this.BodyType = BodyType;
      this.OnGround = OnGround;
      this.CollisionGroups = CollisionGroups;
    }

    public PhysicsBody() {
    }
  }
}
