// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class PlayerInput {
    [DataMember(Name = "player_id")]
    public uint PlayerId;
    [DataMember(Name = "horizontal_axis")]
    public float HorizontalAxis;
    [DataMember(Name = "jump_pressed")]
    public bool JumpPressed;
    [DataMember(Name = "input_sequence")]
    public uint InputSequence;

    public PlayerInput(
        uint PlayerId,
        float HorizontalAxis,
        bool JumpPressed,
        uint InputSequence
    ) {
      this.PlayerId = PlayerId;
      this.HorizontalAxis = HorizontalAxis;
      this.JumpPressed = JumpPressed;
      this.InputSequence = InputSequence;
    }

    public PlayerInput() {
    }
  }
}
